### ISSUE TITLE
Can't get eos account public key

### ISSUE THREAD

**Issue by peterhelin** [GetScatter/ScatterWebExtension#154]
the doc says that through requiring specific fields:
        const requiredFields = {
            accounts:[ { blockchain:'eos', chainId:'aca....' } ]
        };
then we can get:
        {
            accounts:[
                { blockchain:'eos', name:'testaccount', authority:'active', publicKey:'EOS6MRyAjQq...' },
            ]
        }
but in reality, i can only get this
        {
            accounts:[
                { blockchain:'eos', name:'testaccount', authority:'active'},
            ]
        }
so the question is how I get the publicKey of my eos account?
Since I have imported my private key into Scatter,  it's obvious that I can get my publicKey whenever I want...

**Comment by nsjames** [comment]
Scatter Classic ( this extension ) doesn't provide the `publicKey` when returning EOS account data, only Scatter Desktop. 
I'd advise looking into `scatter-js` ( https://github.com/GetScatter/scatter-js ) and adding support for Desktop ASAP, as Classic will be deprecated in favor of Desktop soon.

**Comment by jurosh** [comment]
@nsjames wouldn't be possible to update extension to include account `publicKey`?
I can imagine that transition process from ScatterExtension to ScatterDesktop would take quite long time...

**Comment by nsjames** [comment]
For the project the process of transitioning over to `scatterjs` is only a few lines of code.

For the users, though that process might take a bit longer it's a **very** advised process due to security concerns. All work on Scatter Classic has stopped unless it's a security centric bug that _can be handled_. Otherwise, we don't want to get hopes up that it will still be maintained as it send the wrong message.

Read this article to get an elaborate reasoning behind this (obviously stern) decision.
https://medium.com/@nsjames/the-blockchain-isnt-just-for-web-applications-silly-rabbit-926a4ea5ccd1
