### ISSUE TITLE
when the password length is 12, why is the mnemonic eaqual to the password?

### ISSUE THREAD

**Issue by jason-zuo** [GetScatter/ScatterWebExtension#175]
if(password.split(' ').length >= 12) {
                console.log(11)
                seed = await Mnemonic.mnemonicToSeed(password);
                mnemonic = password;
            }

**Comment by nsjames** [comment]
It's not password length 12, it's words length twelve. 
`password.split(' ')` means it splits the password into an array of words using `space` as the delimiter and then counts the words. Because of the way Scatter works your mnemonic is a backup for your password, and entering it anywhere that accepts a password also works.
