### ISSUE TITLE
Provide relevant ricardian contract for actions

### ISSUE THREAD

**Issue by friedger** [GetScatter/ScatterWebExtension#83]
As stated in the constitution, a ricardian contract shall come with each contract.
It would be good to have at least a link to that document.

See
https://github.com/EOS-Mainnet/governance/blob/master/eosio.system/eosio.system-clause-constitution-rc.md#article-vii---open-source

**Comment by nsjames** [comment]
Ricardian contracts are now supports per action but not for the constitution yet.
cb63016ec551ec611d1a4ccb0a0d12a75c6c1ef3

Constitution will be displayed every time a user imports a new EOS account into Scatter.

This is not yet built into the zip because fetching ricardian contracts add significant overhead ( 2 - 6 seconds ) to the user-experience. 

I've added a ticket on the EOSIO repo about a way to solve this here: https://github.com/EOSIO/eos/issues/4222

**Comment by abourget** [comment]
When are we going to see ricardian contracts?

**Comment by nsjames** [comment]
@abourget Ricardians were removed from Scatter due to security concerns. 
With the way that they are currently written, there's no safe way to parse them.
